#
# Makefile for ACPICA Core interpreter
#

obj-y += tbxface.o
obj-y += tbinstal.o
obj-y += tbutils.o
obj-y += tbxfroot.o

obj-y += utalloc.o
obj-y += utmisc.o
obj-y += utglobal.o
obj-y += utxferror.o

