# ==========================================================================
# Build system
# ==========================================================================

include $(SCRIPTS_DIR)/Makefile.include

GRUBMKRESCUE := grub-mkrescue
GENSYMS := $(ARCH_SCRIPTS_DIR)/gen_sym_file.sh
GENSECS := $(ARCH_SCRIPTS_DIR)/gen_sec_file.sh

NAUT_ISO := $(OUTPUT_DIR)/nautilus.iso
NAUT_SYM := $(OUTPUT_DIR)/nautilus.syms
NAUT_SEC := $(OUTPUT_DIR)/nautilus.secs

isoimage: $(NAUT_ISO) FORCE

$(NAUT_SYM): $(NAUT_BIN)
	$(call quiet_cmd,GENSYMS,$@)
	$(Q)$(GENSYMS) $(NAUT_SYM) tmp.sym

$(NAUT_SEC): $(NAUT_BIN)
	$(call quiet_cmd,GENSECS,$@)
	$(Q)$(GENSECS) $(NAUT_SEC) tmp.sec

$(NAUT_ISO): $(NAUT_BIN) $(NAUT_SYM) $(NAUT_SEC)
	$(call quiet_cmd,MKISO,$@)
	$(Q)mkdir -p .iso/boot/grub
	$(Q)cp configs/grub.cfg .iso/boot/grub
	$(Q)cp $(NAUT_BIN) $(NAUT_SYM) $(NAUT_SEC) .iso/boot
	$(Q)$(GRUBMKRESCUE) -o $(NAUT_ISO) .iso
	$(Q)rm -rf .iso

DEFAULT_RULES += $(NAUT_ISO)

CLEAN_RULES += x64-clean-isoimage

x64-clean-isoimage:
	$(Q)rm -rf .iso
	$(Q)rm -f tmp.sym
	$(Q)rm -f tmp.sec
	$(Q)rm -f $(NAUT_ISO)
	$(Q)rm -f $(NAUT_SYM)
	$(Q)rm -f $(NAUT_SEC)

FORCE:

