
obj-y += \
	nautilus/ \
	arch/ \
	dev/ \
	test/ \
    compat/ \
	fs/  \

obj-$(NAUT_CONFIG_ARCH_X86) += \
	gc/  \
	rt/ \
	net/ \
	acpi/ \

obj-$(NAUT_CONFIG_CXX_SUPPORT) += cxx/
obj-$(NAUT_CONFIG_LEGION_RT) += legion_runtime/
obj-$(NAUT_CONFIG_LOAD_LUA) += lua_src/
obj-$(NAUT_CONFIG_RUST_SUPPORT) += rust/
obj-$(NAUT_CONFIG_ASPACES) += aspace/
obj-$(NAUT_CONFIG_ALLOCS) += alloc/

obj-$(NAUT_CONFIG_USE_WLLVM) += pass/
